  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - com.amazon::LambdaQuarkus

  Resources:
    ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: prod

    LambdaQuarkusFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtime
        Runtime: provided
        CodeUri: target/function.zip
        MemorySize: 256
        Policies:
          - DynamoDBCrudPolicy:
              TableName: Customers
        Timeout: 15
        Environment:
          Variables:
            # see https://quarkus.io/guides/amazon-lambda-http
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          LambdaQuarkusGetAll:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /Customers
              Method: GET
          LambdaQuarkusGetCustomer:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /Customers/{CustomerId}
              Method: GET
          LambdaQuarkusDeleteCustomer:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /Customers/{CustomerId}
              Method: DELETE
          LambdaQuarkusAddCustomer:
            Type: Api
            Properties:
              RestApiId: !Ref ApiGatewayApi
              Path: /Customers
              Method: POST

    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: CustomerId
            AttributeType: S
        KeySchema:
          - AttributeName: CustomerId
            KeyType: HASH

  Outputs:
    ApiUrl:
      Description: URL of the Customers listing in the prod stage
      Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/Customers"